### ISSUE TITLE
Boiler control only partly working

### ISSUE THREAD

**Issue by devinfluencer** [diyless/opentherm-thermostat2#1]
Hi I have an old OT Boiler from the 2002 timeframe (OT maybe ver 2.0). It is made by Remeha and OEM labelled by Windhager.
Contrl of the device is not working correctly, the only reaction I got was the hot water temperature display seemed right and shutting of water heating via WIFI worked.
The room temperature seemed not to be sent to the boiled, as it displayed "sensor broken" and began to permanently heat the room. The boiler uses a room temp. of 0 in case the sensor is broken according to the manual. Shutting off heating via WIFI did not work.
Do you think settign the member ID to 11 for Remeha might improve the situation?

**Comment by diyless** [comment]
Hi @devinfluencer ,
The Thermostat2 is compatible with all OpenTherm versions, you can try to set member id.
In general, the thermostat should not send the room temperature to the boiler. It calculates the boiler setpoint based on the target and actual room temperature.
Why do you have "sensor broken"? Do you have the BLE sensor configured as a room sensor or another option?

**Comment by devinfluencer** [comment]
Hi diyless,
I didn't know that about the room temerature. Thanks.
In the meantime I found out some more things:

* The boiler has an undocumented switch manual/auto. I happened to switch it to manual when I was working in the room and didn't notice it. The switch seems to enable the OT functionality. The temp display seems to refer to a sensor that can be attached to the boiler but is not there. That explains the 'sensor broken' message.

* In setting auto I am using the Thermostat2 currently and it works (almost) as expected. Due to the warm weather I didn't try the heating itself yet, but I used the water heating. The water reservoir temp looks fine and corresponds to the temperature displayed on the boiler. I can start/stop the water heating and it goes to idle when the temperature setting _on the boiler_ is reached. I set a lower water temp on Thermostat2 but it heats further. After going to idle I switched off water heating, as I have a solar thermic water heating that aids the water temp during the day. Do you have an explanation for that or is it an implementation detail of my boiler?

* HA integration works fine. I noticed the two temperature number display on the web frontend of Thermostat2 and in HA are swapped. In HA the aim temp is big and the current temp is small, on the web frontend and of the device display the current temp is big. I prefer the latter, so I might change the HA configuration.

Thomas

**Comment by devinfluencer** [comment]
Hi again,
I can confirm now that the Thermostat works fine with my heating.
However, I'm missing one feature in the firmware that I now implemented on HA: Heating the water by schedule or only once in the morning.
A firmware implemntation would continue to work 
In case the HA connection fails
How about this?
Thanks,
Thomas

**Comment by diyless** [comment]
DHW schedule is on our todo list

**Comment by diyless** [comment]
Hi

The water schedule is on our schedule. We will take a look into it once
after we complete some HA support extension (adding new sensors and
resolving a bug with 2x thermostats within the same HA instance).

**Comment by devinfluencer** [comment]
Thank you for your great work!
