### ISSUE TITLE
Sensor failure over MQTT

### ISSUE THREAD

**Issue by Skons** [diyless/opentherm-thermostat2#4]
It seems that when the thermostat reports an error, i.e. sensor error, then this can only be read at the thermostat self. Is it possible that is also reported over MQTT? This way notifications can be set if something is wrong.

**Comment by diyless** [comment]
We have ongoing update which would contain a separate availability topic for BLE sensor (online/offline). We can also add a similar for the internal sensor. Would that be sufficient?

**Comment by Skons** [comment]
That is a neat feature, but i had issues with my MQTT sensor, at least diyless reported an error while mine is configured with mqtt. I cant reproduce though, so thats why i want to know if something is going on...

**Comment by diyless** [comment]
Your MQTT sensor might be publishing too rarely, so our thermostat reports as a failure. If there was no message for at least 2 minutes - thermostat treats it as a failure

**Comment by Skons** [comment]
What is saw was that my temperature sensors where updating their value, and it seemed to be resembled in the values reported by the thermostat (Thought there was a difference between the temperatures, the temp was updated). This has happened 2 times, which of one saw sensor error on the thermostat (the other time i did not take a look). Maybe there was a problem for 2 minutes and the thermostat did not recover? Having the diyless reporting the error would help me. if it does not report an error for the sensor, but the sensor is in error state then mqtt could be having a problem. If it reports an error for the sensor over mqtt, something is going on with the sensor, not mqtt.

**Comment by diyless** [comment]
We will add a separate availability property for the each sensor, so you can track its availability
https://github.com/diyless/opentherm-thermostat/blob/main/README.md

**Comment by Skons** [comment]
I see states available in the new version. Will keep an eye if it works or not and come back to you if i need some help. Thanks for your support
