### ISSUE TITLE
Temperature through an API

### ISSUE THREAD

**Issue by Skons** [diyless/opentherm-thermostat2#6]
The diyless thermostat allows for external sensors which is very nice. In my case i have to have a MQTT sensor, but i would like to be able to provide the temperature through an api. This allows me to have less components to manage it all, less components means I would be lesser prone to a possible failure of a component, which attributes to the WAF. If it is possible, then it would be nice to know how often the api needs to be updated with a new value.

**Comment by diyless** [comment]
WAF is quite important)
through an api - you mean a HTTP REST api?

**Comment by Skons** [comment]
Yeah, rest api

**Comment by diyless** [comment]
okay, we will have a very minimal restapi for 2.1 update (allow to set a room temperature). Further it will be extended. Also, currently you can use HTTP calls to save configuration or sensor settings. All of those are easy to peek using a browser developer tools.

**Comment by Skons** [comment]
The browser developer tools was where i already had been going, i am implementing an software update notification thingy and i needed that :)

**Comment by diyless** [comment]
Any other suggestions to squeeze into upcoming version regarding the REST API? https://github.com/diyless/opentherm-thermostat/blob/main/README.md

**Comment by Skons** [comment]
No, this feature is sufficient for me. Thanks!

**Comment by Skons** [comment]
Thank you, works as expected 👍

**Comment by diyless** [comment]
Have you tried updating to the 2.1 version?

**Comment by Skons** [comment]
yes, i said that it worked ;). i can update the temperature with a rest api call
